FROM python:3.10.6-alpine3.16

LABEL maintainer = "vinita-220340126032"

# create current directory in container if not exist
WORKDIR /usr/src/pythoncodes            

COPY square.py /usr/src/pythoncodes 

CMD ["python3","square.py"]